version: '3.8'

services:
  user-service-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "9229:9229"  # Debug port
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/user_service
      - MONGODB_TEST_URI=mongodb://mongodb-test:27017/user_service_test
      - JWT_SECRET=dev-secret-key
      - CORS_ORIGIN=http://localhost:3000
      - API_DOCS_ENABLED=true
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb
      - mongodb-test
    restart: unless-stopped
    networks:
      - user-service-network
    command: npm run dev:debug

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_dev_data:/data/db
    restart: unless-stopped
    networks:
      - user-service-network

  mongodb-test:
    image: mongo:6.0
    ports:
      - "27018:27017"
    tmpfs:
      - /data/db
    restart: unless-stopped
    networks:
      - user-service-network

volumes:
  mongodb_dev_data:

networks:
  user-service-network:
    driver: bridge
